# Configuracion del servidor
spring.application.name=ms-notificaciones-consumer
server.port=8083

# Configuracion de RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configuracion de listener
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.max-attempts=3

# Configuracion de exchanges
rabbitmq.exchange.notificaciones=exchange.notificaciones
rabbitmq.exchange.dlx=exchange.dlx

# Configuracion de colas
rabbitmq.queue.notificaciones=cola.notificaciones
rabbitmq.queue.notificaciones.dlq=cola.notificaciones.dlq

# Configuracion de routing keys
rabbitmq.routing.notificacion.enviar=venta.notificacion.enviar
rabbitmq.routing.error.notificacion=error.notificacion

# Logging
logging.level.cl.duoc.asyncorders=DEBUG
logging.level.org.springframework.amqp=DEBUG
